services:
  campuslands-package:
    build:
      context: .
      dockerfile: Dockerfile.package
      args:
        REPOSITORY_NAME: campuslands-dev-nodejs-express
        REPOSITORY_URL: https://github.com/anndreloopez012/campuslands-dev-nodejs-express
    image: ghcr.io/anndreloopez012/campuslands-dev-nodejs-express:local
    container_name: campuslands-dev-nodejs-express-docs
    ports:
      - "8080:80"
    restart: unless-stopped
